# This workflow builds an aar and deploys it to Maven Central

name: Deploy to Maven Central

on: workflow_dispatch

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Deploy to Maven Central
        run: |
          ./gradlew publishReleasePublicationToMavencentralRepository \
            -PossrhSigningKey="${{ secrets.MAVEN_CENTRAL_KEY }}" \
            -PossrhSigningPassword="${{ secrets.MAVEN_CENTRAL_PASSWORD }}" \
            -PossrhUsername="${{ secrets.MAVEN_CENTRAL_USERNAME }}" \
            -PossrhPassword="${{ secrets.MAVEN_CENTRAL_PASSWORD }}"